from abc import ABC, abstractmethod
from typing import Protocol
class MenuButton(Protocol):
    def onClick(self) -> None: ...
    def clickable(self) -> bool: ...
    def onClose(self)-> None: ...

class Dialog (ABC):
